export function getReleaseManifest() {
  return {
    product: "KRATOS Terminal",
    version: "4.0.0",
    releaseChannel: "main",
    frontendRoutes: [
      "/",
      "/gods-eye",
      "/markets",
      "/arbitrage",
      "/news-impact",
      "/stocks",
      "/sports",
      "/trading",
      "/mirofish",
      "/psplc",
      "/posh",
      "/pbql",
      "/portfolio",
      "/deploy",
    ],
    apiRoutes: [
      "/api/health",
      "/api/health/deep",
      "/api/deploy/readiness",
      "/api/release/summary",
      "/api/markets",
      "/api/news",
      "/api/pbql",
      "/api/pbql/saved",
      "/api/session",
      "/api/portfolio",
      "/api/positions",
      "/api/watchlist",
      "/api/commands",
      "/api/trade/simulate"
    ],
    persistence: [
      "watchlist_items",
      "saved_pbql_queries",
      "simulated_positions",
      "terminal_command_history",
    ],
    capabilities: [
      "interactive globe",
      "PBQL queries",
      "trade simulation",
      "runtime health",
      "deploy readiness diagnostics",
      "authenticated watchlists",
      "saved queries",
      "simulated positions",
      "command history",
    ],
  };
}
